using MOBA.Game.Scenes;

namespace MOBA.Game.Models;

/// <summary>
/// Runtime map description: dimensions plus the references to the terrain
/// ground mesh and the precomputed navmesh blob. Static map content
/// (buildings, monsters, …) live as their own actors in the scene, not as
/// lists on the map — this class is just the world's geographic header.
/// </summary>
public sealed class Map
{
    public Map(
        float width,
        float length,
        string terrainMesh = "dimension-rift",
        string navMesh = "dimension-rift.navmesh")
    {
        Width = width;
        Length = length;
        TerrainMesh = terrainMesh;
        NavMesh = navMesh;
    }

    public float Width { get; }

    public float Length { get; }

    public string TerrainMesh { get; }

    /// <summary>
    /// Filename (relative to <c>assets/maps/</c>) of the precomputed navmesh blob.
    /// Generated by <c>tools/MOBA.Tools.NavMeshGen</c>; consumed via the
    /// <see cref="MOBA.Engine.Core.AssetCache{TKey,TAsset}"/> registered by
    /// <c>AddNavMeshCache</c>.
    /// </summary>
    public string NavMesh { get; }

    /// <summary>Built from a deserialised <see cref="MapDefinition"/> (JSON).</summary>
    public static Map FromDefinition(MapDefinition definition) =>
        new(
            definition.Width,
            definition.Length,
            definition.TerrainMesh ?? "dimension-rift",
            definition.NavMesh ?? "dimension-rift.navmesh");

    /// <summary>
    /// Skeleton fallback: 150 × 150 world units (≈ LoL-scale playing field in our unit).
    /// Use only where loading from <c>assets/scenes/*.json</c> is impractical
    /// (e.g. unit tests, scripted simulations).
    /// </summary>
    public static Map LeagueSized() => new(150f, 150f);
}
