<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Silk.NET.Windowing" />
        <PackageReference Include="Silk.NET.OpenGL" />
        <PackageReference Include="Silk.NET.Input" />
        <PackageReference Include="Silk.NET.Maths" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MOBA.Engine.Core\MOBA.Engine.Core.csproj" />
        <ProjectReference Include="..\MOBA.Engine.Graphics\MOBA.Engine.Graphics.csproj" />
        <ProjectReference Include="..\MOBA.Engine.Networking\MOBA.Engine.Networking.csproj" />
        <ProjectReference Include="..\MOBA.Game\MOBA.Game.csproj" />
        <ProjectReference Include="..\MOBA.Game.Client\MOBA.Game.Client.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\assets\**\*.*">
            <Link>assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
